# https://taskfile.dev/

version: '3'

interval: 1s

vars:
  JS_BUNDLE: public/app.js
  CSS_BUNDLE: public/app.css

  EXE: app{{exeExt}}

tasks:
  default:
    desc: Build and run the web app
    aliases: [run]
    cmds:
      - task: build
      - ./{{.EXE}}

  build:
    desc: Build the web app
    deps: [js, css]
    cmds:
      - go build -v -o {{.EXE}} ./app.go
    sources:
      - '**/*.go'
      - '{{.JS_BUNDLE}}'
      - '{{.CSS_BUNDLE}}'
    generates:
      - '{{.EXE}}'

  js:
    desc: Bundle JS using esbuild
    cmds:
      - esbuild --bundle --minify assets/js/main.js > {{.JS_BUNDLE}}
    sources:
      - assets/js/**/*.js
    generates:
      - '{{.JS_BUNDLE}}'

  css:
    desc: Bundle CSS using esbuild
    cmds:
      - esbuild --bundle --minify assets/css/main.css > {{.CSS_BUNDLE}}
    sources:
      - assets/css/**/*.css
    generates:
      - '{{.CSS_BUNDLE}}'

  clean:
    desc: Clean every generated file
    cmds:
      - rm -f {{.CSS_BUNDLE}}
      - rm -f {{.JS_BUNDLE}}
      - rm -f {{.EXE}}
